### ISSUE TITLE
GetVehicleParamsEx

### ISSUE THREAD

**Issue by Kanti** [crodriguespt/SAMPHP#17]
Should return -1;
> Note:
> If a parameter is unset (SetVehicleParamsEx not used beforehand) the value will be -1 ('unset').

returns true;

**Comment by crodriguespt** [comment]
There isn't anything I can do to fix that.
SAMPHP is just a bridge to "connect" PHP to the SA-MP server, so, everything you will get in PHP is returned from SAMPGDK(Plugin base).

Check file
``` bindings_vehicles.hpp ```
